### ISSUE TITLE
Importing nftx-protocol-v3 as a lib in a Foundry project causes resolution issues

### ISSUE THREAD

**Issue by Zodomo** [NFTX-project/nftx-protocol-v3#108]
When importing interfaces from nftx-protocol-v3 into a Foundry project, there are resolution errors involving the openzeppelin-contracts library. It appears Foundry wants the library to be installed in my project. When I attempted to do `forge install openzeppelin/openzeppelin-contracts --no-commit` to install them, I continue to get the same following error:

![image](https://github.com/NFTX-project/nftx-protocol-v3/assets/114717981/69aff338-6c5c-43f8-995f-fc39269e2179)

This is because the current version of openzeppelin-contracts is v5.0.2, while NFTX V3 is using v4.6.0. The issue could be resolved with explicit import paths in your contracts and interfaces, but I resolved it for my project with `forge install openzeppelin/openzeppelin-contracts@release-v4.6`. This installs the correct OZ library in my lib folder where Foundry is configured to look for it by your repo.

**Comment by apoorvlathey** [comment]
I created a new foundry project with `foundry init`
Then ran: `forge install https://github.com/NFTX-project/nftx-protocol-v3.git` and it installed all the libs & dependencies including openzeppelin `v4.6.0` without any issue.

I think if your parent repo is using the same key `@openzepplin` for remappings then the compiler might be referencing `./lib/openzeppelin-contracts` instead of the intended `./lib/nftx-protocol-v3/lib/openzeppelin-contracts`?

**Comment by Zodomo** [comment]
Ah yeah you're right, it was imports having to do with the parent project. Sorry for the false alarm!
